function createfigure(X1, signal_vector1)
%CREATEFIGURE(X1, signal_vector1)
%  X1:  vector of plot x data
%  SIGNAL_VECTOR1:  vector of plot y data

%  Auto-generated by MATLAB on 14-Oct-2025 15:39:04

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create plot
plot1 = plot(X1,signal_vector1,'DisplayName','data1','ZDataSource','');

% The following line demonstrates an alternative way to create a data tip.
% datatip(plot1,56.06,2176);
% Create datatip
datatip(plot1,'DataIndex',5607);

% Create ylabel
ylabel('ADC');

% Create xlabel
xlabel('time');

% Create title
title('load cell adc signal');

box(axes1,'on');
hold(axes1,'off');
% Set the remaining axes properties
set(axes1,'XGrid','on','ZGrid','on');
% Create legend
legend(axes1,'show');

